steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/portfolio-website-378500/portfolio-website-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/portfolio-website-378500/portfolio-website-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-website-backend'
      - '--image=gcr.io/portfolio-website-378500/portfolio-website-backend'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'